### ISSUE TITLE
WeChat Pay not showing up in Woocommerce Settings

### ISSUE THREAD

**Issue by brianvertweb** [froger-me/woo-wechatpay#12]
Woocommerce version :4.3.1

In Woocommerce > Settings > Payments... the payment gateway does not show so their is no wan to configure it.

**Comment by froger-me** [comment]
Hi @brianvertweb ; have you installed and configured the WP Weixin plugin that Woo WeChatPay depends on?

**Comment by brianvertweb** [comment]
@froger-me Thanks for the reply, i did not see that in the steps. 

I also just noticed 2 different plugins....

Currently activated
-Payment gateway for WooCommerce - Woo WeChatPay
-WP Weixin

Not activated
-WP Weixin Pay

Should disable the first onw and activate "WP Weixin Pay"

**Comment by froger-me** [comment]
Actually no:
- WP Weixin Pay is an O2O plugin not requiring WooCommerce that adds a payment screen to your phone to show to other WeChat users (think: I buy a bottle of water and pay it with WeChat Pay by scanning a code instead of cash)
- Payment gateway for WooCommerce - Woo WeChatPay is a payment gateway for WooCommerce, like PayPal and others
- WP Weixin is the core plugin that integrate WordPress with WeChat, doing all the necessary remote calls to WeChat servers (including the ecommerce calls, hence why it is necessary)

So in your case, you need "WP Weixin" and "Payment gateway for WooCommerce - Woo WeChatPay" activated and configured. Here "configured" for WP Weixin specifically means that, minimally, you need:

In "Main Settings" on the WP Weixin configuration page:
- Enable checkbox ticked
- WeChat App ID filled
- WeChat App Secret filled

In "WeChat Pay Settings" on the WP Weixin configuration page:
- WeChat Merchant App ID  filled (if and only if it is different from the above WeChat App ID)
- WeChat Merchant ID filled
- WeChat Merchant Key filled
- PEM certificate prefix filled
- PEM certificate files path filled

All these values have help text to point to where to find them in the WeChat backends, and are unusually verbose, trying to keep a balance between clutter and help. This is because not only are there files to download from the payment backend and put on your server (certificates), there is also a lot of counterpart configuration to do in the WeChat backends as well (namely https://mp.weixin.qq.com/ and https://pay.weixin.qq.com/).

I haven't outlined here the other requirements such as ICP number, type of official account, necessity to have https enabled, compatible permalinks structure, because it's all in both plugins' README.MD files, or in the help text of the associated fields.

What I am trying to say is that WeChat Pay (or WeChat integration itself) is not plug'n'play and sympathize with the possible frustration you may experience (trust me, I coded the damn thing :-D ). The plugins are attempting to facilitate all that but there are limitations due to the architectural choices made by Tencent.

I do hope what is listed above will be able to point you to the right directions.

**Comment by brianvertweb** [comment]
Thanks for the thorough reply! I will give it a go! Thanks again.

**Comment by froger-me** [comment]
Please let me know when the gateway settings appear - I'll then close the issue.
If you have any other problem (bugs only though, difficulty with configuration is out of support scope), feel free to open a new issue :).

**Comment by brianvertweb** [comment]
hello, so i checked the official account and got the WeChat APP ID and secret. In the same backend i went to the WeChat Pay section and i can see the same APP id in both places. Im still getting the configuration error message

**Comment by froger-me** [comment]
Hi @brianvertweb ,

You didn't mention any error message in this thread - I am not sure what it refers to.
You mention getting the WeChat Pay app ID and secret in the Official Account backend ; this isn't right, you also need Merchant ID and Merchant Key.

There are 2 backends, 1 for the Official account, 1 for WeChat Pay (namely https://mp.weixin.qq.com/ and https://pay.weixin.qq.com/). You need to have access to both of these to enable payment. All these details are included in the inline help on the configuration page, but [this tutorial](https://shinecloud.com.cn/2020/03/20/wp-weixin-chajianshiyongjiaocheng/) written by a Chinese user (in Chinese) may also be helpful.

It seems what you need is help with configuration ; Github issues are for bug reports, so I am going to close the issue.

If you would like me to get involved with your setup, feel free to contact me directly by email at alex@froger.me or WeChat (ID: danfroal). This is something I can help with for a fee payable by WeChat (RMB 500 for 3h max upfront, then RMB 200 for each additional hour spent ; guarantee of best effort, non-refundable) and access to your server via SSH and WordPress admin (and any other credentials necessary, or active participation in the troubleshooting process, share screen or screenshots for step-by-step configuration of the WeChat Pay account).
